### ISSUE TITLE
[Question] C# Work-around

### ISSUE THREAD

**Issue by AlbinoDrought** [jodoglevy/gargl#15]
Hello,

I have been wanting to try out this framework but I write in C#. After dabbling around a bit I decided to add a C# generator. [See Yahoo template output here](https://gist.github.com/AlbinoDrought/cc456aa8522699ce36ed) The problem is, I am having trouble with setting request headers. The way I am doing it now works, but it requires a separate include file ([straight from StackOverflow](http://stackoverflow.com/a/23070923)).

[Generator](https://github.com/AlbinoDrought/gargl/blob/master/generators/JavaGenerator/src/main/java/gargl/generators/CSharpClassGenerator.java)

[Include](https://github.com/AlbinoDrought/gargl/blob/master/includes/HTTPWebRequestExtensions.cs)

The problem is that the simple way to add headers would be `req.Headers.Add("User-Agent", "TestAgent");` but User-Agent, among many other headers, are restricted and throw an exception when modified incorrectly. They must be set by `req.UserAgent = "TestAgent";`. You can see how this does not match the traditional style of Gargl.

So my question is... does anyone have a better way to do this? I was thinking about adding the include to the generated file, but it may get bulky if using multiple templates. Is the best way to go just to add this logic into the Generator itself (and spit out valid values)?

**Comment by jodoglevy** [comment]
Hey Sean, thanks for contributing. My opinion would be to add the logic to the generator, but I'll defer to @mross22 on this since he is our C# expert.
