### ISSUE TITLE
Response field

### ISSUE THREAD

**Issue by burgyl** [jodoglevy/gargl#25]
Hi,

Thank you for your awesome tool !

I tried it with a search engine and added a response field like in your demonstration video. The response I have when I test it isn't filtered with the css selector, I have the entire HTML file.

Did I not understand something ?

Regards,
Guduche

**Comment by JAL9302** [comment]
Hi,

Can you provide more details? What website? What request/response were you recording? What css selector did you use? Etc. Otherwise, there's no way for me to debug what's going on.

**Comment by burgyl** [comment]
It's with local.ch, I'm trying a request. Here is a screenshot http://prntscr.com/ffoza9

**Comment by AlbinoDrought** [comment]
For what it's worth, the selector seems to work for me:

![image](https://cloud.githubusercontent.com/assets/852873/26764013/8dbfe000-4913-11e7-88e7-fe3189a7f3ca.png)

Request:

![image](https://cloud.githubusercontent.com/assets/852873/26764019/b15e0c12-4913-11e7-83f7-fc60ef9d4cd7.png)

**Comment by burgyl** [comment]
Yes, me too.
My problem is when I test it with Powershell. The content I receive is simply all the HTML page without filtering it, like it does here with the Test Selector.
I did it exactly how jodoglevy did it in [his demo video](https://www.youtube.com/watch?v=f-3U7o046l0)

**Comment by JAL9302** [comment]
I'm pretty sure the video you link to doesn't show the generated PowerShell module using the CSS selector response field filtering capability -- it only shows the test button in the Gargl Chrome extension using that. Response field filtering by CSS selector is not currently supported in generated PowerShell modules. It is supported in generated JavaScript packages, and in the [Gargl Python project](https://github.com/KarolTx/pygargl).
